BEGIN
    -- Tablas más débiles (dependientes)
    EXECUTE IMMEDIATE 'DROP TABLE orden_mantencion CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE planificacion_dotacion CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

-- Tablas dependientes del personal
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE jefe_turno CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE tecnicos CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE operario CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

-- Tablas intermedias
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE maquina CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE turno CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

-- Tabla principal del personal
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE personal CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

-- Tablas de apoyo
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE planta CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE comuna CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE region CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE afp CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE prevision_salud CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

-- =============================
-- TABLAS FUERTES
-- =============================

CREATE TABLE REGION (
    id_region NUMBER(5) PRIMARY KEY,
    nombre VARCHAR2(25 CHAR) UNIQUE NOT NULL
);

CREATE TABLE COMUNA (
    id_comuna NUMBER(5) GENERATED BY DEFAULT AS IDENTITY(START WITH 1050 INCREMENT BY 5),
    nombre VARCHAR2(35 CHAR) NOT NULL,
    id_region NUMBER(5) NOT NULL,
    CONSTRAINT pk_comuna PRIMARY KEY (id_comuna),
    CONSTRAINT fk_comuna_region FOREIGN KEY (id_region)
        REFERENCES REGION (id_region)
);

CREATE TABLE AFP (
    id_afp NUMBER(5) PRIMARY KEY,
    nombre VARCHAR2(25 CHAR) UNIQUE NOT NULL
);

CREATE TABLE PREVISION_SALUD (
    id_prevision NUMBER(5) PRIMARY KEY,
    nombre VARCHAR2(30 CHAR) UNIQUE NOT NULL
);

CREATE TABLE PLANTA (
    id_planta NUMBER(5) GENERATED BY DEFAULT AS IDENTITY (START WITH 45 INCREMENT BY 1) PRIMARY KEY,
    nombre VARCHAR2(25 CHAR) NOT NULL,
    direccion VARCHAR2(50 CHAR) NOT NULL,
    id_comuna NUMBER(5) NOT NULL,
    CONSTRAINT fk_planta_comuna FOREIGN KEY (id_comuna)
        REFERENCES COMUNA (id_comuna)
);

-- =============================
-- TABLA PERSONAL Y DERIVADAS
-- =============================

CREATE TABLE PERSONAL (
    rut VARCHAR2(15 CHAR) PRIMARY KEY,
    nombre VARCHAR2(25 CHAR) NOT NULL,
    appaterno VARCHAR2(25 CHAR) NOT NULL,
    apmaterno VARCHAR2(25 CHAR) NOT NULL,
    fecha_contratacion DATE NOT NULL,
    sueldo_base NUMBER(10,2) NOT NULL,
    estado_activo CHAR(1 CHAR) NOT NULL,
    jefe_rut VARCHAR2(15 CHAR),
    cargo VARCHAR2(25 CHAR) NOT NULL,
    id_afp NUMBER(5) NOT NULL,
    id_prevision NUMBER(5) NOT NULL,
    id_planta NUMBER(5) NOT NULL,
    CONSTRAINT ck_estado_activo CHECK (estado_activo IN ('S','N')),
    CONSTRAINT ck_cargo CHECK (cargo IN ('Jefe','Operario','Tecnico')),
    CONSTRAINT fk_personal_jefe FOREIGN KEY (jefe_rut) REFERENCES PERSONAL (rut),
    CONSTRAINT fk_personal_afp FOREIGN KEY (id_afp) REFERENCES AFP (id_afp),
    CONSTRAINT fk_personal_prevision FOREIGN KEY (id_prevision)
        REFERENCES PREVISION_SALUD (id_prevision),
    CONSTRAINT fk_personal_planta FOREIGN KEY (id_planta) REFERENCES PLANTA (id_planta)
);

-- =============================
-- TABLAS DERIVADAS DEL PERSONAL
-- =============================

CREATE TABLE JEFE_TURNO (
    rut VARCHAR2(15 CHAR) PRIMARY KEY,
    area_responsable VARCHAR2(20 CHAR) NOT NULL,
    max_operarios NUMBER(2) NOT NULL,
    CONSTRAINT fk_jefeturno_personal FOREIGN KEY (rut)
        REFERENCES personal (rut)
);

CREATE TABLE TECNICOS (
    rut VARCHAR2(15 CHAR) PRIMARY KEY,
    especialidad VARCHAR2(15 CHAR) NOT NULL,
    nivel_certificacion VARCHAR2(15 CHAR),
    tiempo_respuesta VARCHAR2(20 CHAR) NOT NULL,
    CONSTRAINT fk_tecnico_personal FOREIGN KEY (rut)
        REFERENCES PERSONAL (rut)
);

CREATE TABLE OPERARIOS (
    rut VARCHAR2(15 CHAR) PRIMARY KEY,
    categoria_proceso VARCHAR2(20 CHAR) NOT NULL,
    certificacion VARCHAR2(20 CHAR),
    hrs_por_turno NUMBER(2) DEFAULT 8 NOT NULL,
    CONSTRAINT ck_categoria_proceso CHECK (categoria_proceso IN ('Caliente','Frío','Inspección')),
    CONSTRAINT fk_operario_personal FOREIGN KEY (rut)
        REFERENCES PERSONAL (rut)
);

-- =============================
-- TABLAS DE MÁQUINAS Y TURNO
-- =============================

CREATE TABLE MAQUINA (
    id_maquina NUMBER(5),
    id_planta NUMBER(5) NOT NULL,
    nombre VARCHAR2(25 CHAR) NOT NULL,
    estado_activo CHAR(1 CHAR) NOT NULL,
    tipo_maquina VARCHAR2(25 CHAR) UNIQUE NOT NULL,
    CONSTRAINT pk_maquina PRIMARY KEY (id_planta, id_maquina),
    CONSTRAINT ck_estado_activo_maq CHECK (estado_activo IN ('S','N')),
    CONSTRAINT fk_maquina_planta FOREIGN KEY (id_planta)
        REFERENCES PLANTA (id_planta)
);

CREATE TABLE TURNO (
    id_turno VARCHAR(15) PRIMARY KEY,
    descripcion VARCHAR2(50 CHAR) UNIQUE NOT NULL,
    hora_inicio CHAR(5 CHAR) NOT NULL,
    hora_termino CHAR(5 CHAR) NOT NULL,
     CONSTRAINT descrip_turno CHECK (descripcion IN ('Mañana','Tarde','Noche'))
);

-- =============================
-- TABLAS DÉBILES (DEPENDIENTES)
-- =============================

CREATE TABLE PLANIFICACION_DOTACION (
    id_planificacion NUMBER(5) PRIMARY KEY,
    rol VARCHAR2(50 CHAR),
    personal_rut VARCHAR2(15 CHAR) NOT NULL,
    id_planta NUMBER(5) NOT NULL,
    id_maquina NUMBER(5) NOT NULL,
    turno_id_turno NUMBER(5) NOT NULL,
    CONSTRAINT fk_dotacion_personal FOREIGN KEY (personal_rut)
        REFERENCES PERSONAL (rut),
    CONSTRAINT fk_dotacion_maquina FOREIGN KEY (id_planta, id_maquina)
        REFERENCES MAQUINA (id_planta, id_maquina),
    CONSTRAINT fk_dotacion_turno FOREIGN KEY (turno_id_turno)
        REFERENCES TURNO (id_turno)
);

CREATE TABLE ORDEN_MATENCION (
    num_orden NUMBER(5) PRIMARY KEY,
    fecha_programada DATE NOT NULL,
    fecha_ejecucion DATE,
    descripcion VARCHAR2(200 CHAR) NOT NULL,
    id_planta NUMBER(5) NOT NULL,
    id_maquina NUMBER(5) NOT NULL,
    tecnicos_rut VARCHAR2(15 CHAR) NOT NULL,
    CONSTRAINT fk_mantencion_maquina FOREIGN KEY (id_planta, id_maquina)
        REFERENCES MAQUINA (id_planta, id_maquina),
    CONSTRAINT fk_mantencion_tecnico FOREIGN KEY (tecnicos_rut)
        REFERENCES TECNICOS(rut),
    CONSTRAINT ck_fecha_ejecucion CHECK(fecha_ejecucion IS NULL 
    OR fecha_ejecucion >= fecha_programada)    
);

CREATE SEQUENCE seq_region START WITH 21 INCREMENT BY 1 NOCACHE NOCYCLE;

--Poblamiento tabla REGION--
INSERT INTO REGION VALUES (seq_region.NEXTVAL, 'Region de Valparaiso');
INSERT INTO REGION VALUES (seq_region.NEXTVAL, 'Region Metropolitana');  


--Poblamiento tabla COMUNA--

INSERT INTO COMUNA(nombre,id_region)
SELECT 'Maipú', r.id_region
FROM region r
WHERE r.nombre = 'Region Metropolitana';

INSERT INTO COMUNA(nombre,id_region) SELECT 'Quilpué', r.id_region
FROM region r
WHERE r.nombre = 'Region de Valparaiso';

--Poblamiento tabla PLANTA--

INSERT INTO PLANTA (nombre, direccion,id_comuna) SELECT 'Planta Oriente',
'Camino Industrial 1234', c.id_comuna FROM comuna c WHERE c.id_comuna = 1050;

INSERT INTO PLANTA (nombre, direccion,id_comuna) SELECT 'Planta Costa',
'Av. Vidrieras 890', c.id_comuna FROM comuna c WHERE c.id_comuna = 1055;

--Poblamiento tabla TURNO--

INSERT INTO TURNO (id_turno, descripcion, hora_inicio, hora_termino) VALUES('M0715','Mañana', '07:00', '15:00');
INSERT INTO TURNO (id_turno, descripcion, hora_inicio, hora_termino) VALUES('N2307','Noche', '23:00', '07:00');
INSERT INTO TURNO (id_turno, descripcion, hora_inicio, hora_termino) VALUES('T1523','Tarde', '15:00', '23:00');

--Consulta 1--
SELECT id_turno ||' - '|| descripcion AS "Turno", 
hora_inicio as "Entrada", 
hora_termino AS "Salida" FROM TURNO WHERE hora_inicio>'20:00' ORDER BY hora_inicio DESC;

--Consulta 2--
SELECT descripcion ||' ('|| id_turno||')'  AS "Turno", 
hora_inicio as "Entrada", 
hora_termino AS "Salida" FROM TURNO WHERE hora_inicio BETWEEN '06:00' AND '14:59' ORDER BY hora_inicio ASC;
