--BORRAR TABLAS SI EXISTEN
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE REGION CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN
        NULL;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE GENERO CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN
        NULL;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE ESTADO_CIVIL CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN
        NULL;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE IDIOMA CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN
        NULL;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE TITULO CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN
        NULL;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE COMUNA CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN
        NULL;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE COMPANIA CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN
        NULL;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE PERSONAL CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN
        NULL;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE TITULACION CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN
        NULL;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE DOMINIO CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN
        NULL;
END;

--CREO TABALAS PARA PODER REFERENCIAR CORRECTAMENTE LAS FK--

CREATE TABLE REGION(
 id_region NUMBER GENERATED BY DEFAULT AS IDENTITY
                 (START WITH 7 INCREMENT BY 2),
    nombre VARCHAR2(25) NOT NULL,
     CONSTRAINT pk_region PRIMARY KEY (id_region)
);

CREATE TABLE GENERO(
id_genero NUMBER(3) NOT NULL,
descripcion_genero VARCHAR2 (25)  NOT NULL,
CONSTRAINT pk_genero PRIMARY KEY(id_genero)
);

CREATE TABLE ESTADO_CIVIL(
id_estado_civil NUMBER(2) NOT NULL,
descripcion_estado_civil VARCHAR2(25),
CONSTRAINT pk_est_civil PRIMARY KEY(id_estado_civil)
);

CREATE TABLE IDIOMA(
id_idioma NUMBER GENERATED BY DEFAULT AS IDENTITY
                 (START WITH 25 INCREMENT BY 3),
    nombre VARCHAR2(50) NOT NULL,
    CONSTRAINT pk_idioma PRIMARY KEY (id_idioma)
);

CREATE TABLE TITULO(
id_titulo NUMBER(3) NOT NULL,
descripcion_titulo VARCHAR2(30),
CONSTRAINT pk_titulo PRIMARY KEY(id_titulo)
);

CREATE TABLE COMUNA(
id_comuna NUMBER(5) NOT NULL,
comuna_nombre VARCHAR2(25) NOT NULL,
cod_region NUMBER(2) NOT NULL,
CONSTRAINT pk_comuna PRIMARY KEY(id_comuna),
CONSTRAINT fk_comuna_region FOREIGN KEY(cod_region) 
   REFERENCES REGION (id_region)
);

CREATE TABLE COMPANIA(
id_empresa NUMBER(2) NOT NULL,
nombre_empresa VARCHAR2(25) NOT NULL UNIQUE,
calle VARCHAR2(50) NOT NULL,
numeracion NUMBER(5) NOT NULL,
renta_promedio NUMBER(10) NOT NULL,
pct_aumento NUMBER(4,3),
cod_comuna NUMBER(5) NOT NULL,
cod_region NUMBER(2) NOT NULL,
CONSTRAINT pk_compania PRIMARY KEY(id_empresa),
CONSTRAINT fk_compania_comuna FOREIGN KEY(cod_comuna)
  REFERENCES COMUNA(id_comuna),
CONSTRAINT fk_compania_region FOREIGN KEY(cod_region) 
  REFERENCES REGION(id_region)
);

CREATE TABLE PERSONAL (
    
    rut_persona NUMBER(8) PRIMARY KEY,
    dv_persona CHAR(1) NOT NULL,
    primer_nombre VARCHAR2(25) NOT NULL,
    segundo_nombre VARCHAR2(25),
    primer_apellido VARCHAR2(25) NOT NULL,
    segundo_apellido VARCHAR2(25),
    fecha_contratacion DATE NOT NULL,
    fecha_nacimiento DATE NOT NULL,
    email VARCHAR2(100) UNIQUE,
    calle VARCHAR2(50),
    numeracion NUMBER(5),
    sueldo NUMBER(5) NOT NULL,
    cod_comuna NUMBER(5) NOT NULL,
    cod_region NUMBER(2) NOT NULL,
    cod_genero NUMBER(3) NOT NULL,
    cod_estado_civil NUMBER(2) NOT NULL,
    cod_empresa NUMBER(2) NOT NULL,
    encargado_rut NUMBER(8), -- Auto-referencia para jefe/supervisor
    CONSTRAINT fk_personal_comuna
        FOREIGN KEY (cod_comuna) 
        REFERENCES COMUNA(id_comuna), 
    CONSTRAINT fk_personal_region
        FOREIGN KEY (cod_region) 
        REFERENCES REGION(id_region),     
    CONSTRAINT fk_personal_genero
        FOREIGN KEY (cod_genero) 
        REFERENCES GENERO(id_genero), 
    CONSTRAINT fk_personal_estado_civil
        FOREIGN KEY (cod_estado_civil) 
        REFERENCES ESTADO_CIVIL(id_estado_civil),
    CONSTRAINT fk_personal_compania
        FOREIGN KEY (cod_empresa) 
        REFERENCES COMPANIA(id_empresa),
    CONSTRAINT fk_personal_encargado
        FOREIGN KEY (encargado_rut) 
        REFERENCES PERSONAL(rut_persona),
    -- Restricciones adicionales
    CONSTRAINT ck_personal_dv
        CHECK (dv_persona IN ('0','1','2','3','4','5','6','7','8','9','K')), 
    CONSTRAINT ck_personal_sueldo
        CHECK (sueldo >= 450000),
    CONSTRAINT ck_personal_fechas
        CHECK (fecha_contratacion >= fecha_nacimiento)
);

CREATE TABLE TITULACION (
    cod_titulo NUMBER(3) NOT NULL,
    persona_rut NUMBER(8) NOT NULL,
    fecha_titulacion DATE NOT NULL,
    CONSTRAINT pk_titulacion
        PRIMARY KEY (cod_titulo, persona_rut),
    CONSTRAINT fk_titulacion_titulo
        FOREIGN KEY (cod_titulo) 
        REFERENCES TITULO(id_titulo),
    CONSTRAINT fk_titulacion_personal
        FOREIGN KEY (persona_rut) 
        REFERENCES PERSONAL(rut_persona)
);
CREATE OR REPLACE TRIGGER trg_titulacion_fecha
BEFORE INSERT OR UPDATE ON TITULACION
FOR EACH ROW
BEGIN
    IF :NEW.fecha_titulacion > SYSDATE THEN
        RAISE_APPLICATION_ERROR(-20001, 'La fecha de titulación no puede ser futura.');
    END IF;
END;

CREATE TABLE DOMINIO (
    -- Clave primaria compuesta (ambas son FK)
    id_idioma NUMBER(3) NOT NULL,
    persona_rut NUMBER(8) NOT NULL,
    nivel VARCHAR2(25) NOT NULL,
    CONSTRAINT pk_dominio PRIMARY KEY (id_idioma, persona_rut),

    CONSTRAINT fk_dominio_idioma FOREIGN KEY (id_idioma) REFERENCES IDIOMA(id_idioma),
    CONSTRAINT fk_dominio_personal FOREIGN KEY (persona_rut) REFERENCES PERSONAL(rut_persona),
    -- Restricción adicional para niveles válidos
    CONSTRAINT ck_dominio_nivel CHECK (nivel IN ('Básico', 'Intermedio', 'Avanzado', 'Nativo'))
);

--Poblamiento del modelo--
--Tabla REGION--
INSERT INTO REGION (nombre) VALUES('Metropolitana');
INSERT INTO REGION (nombre) VALUES('Valparaíso');
INSERT INTO REGION (nombre) VALUES('Biobío');
INSERT INTO REGION (nombre) VALUES('La Araucanía');
INSERT INTO REGION (nombre) VALUES('Los Lagos');
INSERT INTO REGION (nombre) VALUES('Antofagasta');
INSERT INTO REGION (nombre) VALUES('Coquimbo');
INSERT INTO REGION (nombre) VALUES('O’Higgins');
INSERT INTO REGION (nombre) VALUES('Maule');
INSERT INTO REGION (nombre) VALUES('Ñuble');
INSERT INTO REGION (nombre) VALUES('Los Ríos');
INSERT INTO REGION (nombre) VALUES('Aysén');
INSERT INTO REGION (nombre) VALUES('Magallanes');
INSERT INTO REGION (nombre) VALUES('Arica y Parinacota');
INSERT INTO REGION (nombre) VALUES('Tarapacá');


--Tabla IDIOMA--

INSERT INTO IDIOMA (nombre) VALUES ('Español');
INSERT INTO IDIOMA (nombre) VALUES ('Inglés');
INSERT INTO IDIOMA (nombre) VALUES ('Francés');
INSERT INTO IDIOMA (nombre) VALUES ('Alemán');
INSERT INTO IDIOMA (nombre) VALUES ('Italiano');
INSERT INTO IDIOMA (nombre) VALUES ('Portugués');
INSERT INTO IDIOMA (nombre) VALUES ('Chino');

--Tabla COMUNA--

CREATE SEQUENCE seq_comuna
    START WITH 1101
    INCREMENT BY 6;
INSERT INTO COMUNA (id_comuna, comuna_nombre, cod_region)
SELECT seq_comuna.NEXTVAL, 'Santiago', id_region FROM REGION WHERE nombre='Metropolitana';

INSERT INTO COMUNA (id_comuna, comuna_nombre, cod_region)
SELECT seq_comuna.NEXTVAL, 'Valparaíso', id_region FROM REGION WHERE nombre='Valparaíso';

INSERT INTO COMUNA (id_comuna, comuna_nombre, cod_region)
SELECT seq_comuna.NEXTVAL, 'Concepción', id_region FROM REGION WHERE nombre='Biobío';

INSERT INTO COMUNA (id_comuna, comuna_nombre, cod_region)
SELECT seq_comuna.NEXTVAL, 'La Serena', id_region FROM REGION WHERE nombre='Coquimbo';

INSERT INTO COMUNA (id_comuna, comuna_nombre, cod_region)
SELECT seq_comuna.NEXTVAL, 'Antofagasta', id_region FROM REGION WHERE nombre='Antofagasta';

INSERT INTO COMUNA (id_comuna, comuna_nombre, cod_region)
SELECT seq_comuna.NEXTVAL, 'Temuco', id_region FROM REGION WHERE nombre='La Araucanía';

INSERT INTO COMUNA (id_comuna, comuna_nombre, cod_region)
SELECT seq_comuna.NEXTVAL, 'Puerto Montt', id_region FROM REGION WHERE nombre='Los Lagos';

INSERT INTO COMUNA (id_comuna, comuna_nombre, cod_region)
SELECT seq_comuna.NEXTVAL, 'Rancagua', id_region FROM REGION WHERE nombre='O’Higgins';

INSERT INTO COMUNA (id_comuna, comuna_nombre, cod_region)
SELECT seq_comuna.NEXTVAL, 'Iquique', id_region FROM REGION WHERE nombre='Tarapacá';

INSERT INTO COMUNA (id_comuna, comuna_nombre, cod_region)
SELECT seq_comuna.NEXTVAL, 'Arica', id_region FROM REGION WHERE nombre='Arica y Parinacota';


--Tabla COMPANIA--
CREATE SEQUENCE seq_compania
    START WITH 10
    INCREMENT BY 5;

INSERT INTO COMPANIA (id_empresa, nombre_empresa, calle, numeracion, renta_promedio, pct_aumento, cod_comuna, cod_region)
SELECT seq_compania.NEXTVAL, 'Empresa A', 'Av. Siempre Viva', 123, 800000, 0.05, id_comuna, cod_region
FROM COMUNA
WHERE comuna_nombre = 'Santiago';

INSERT INTO COMPANIA (id_empresa, nombre_empresa, calle, numeracion, renta_promedio, pct_aumento, cod_comuna, cod_region)
SELECT seq_compania.NEXTVAL, 'Empresa B', 'Calle Falsa', 456, 900000, 0.06, id_comuna, cod_region
FROM COMUNA
WHERE comuna_nombre = 'Valparaíso';

INSERT INTO COMPANIA (id_empresa, nombre_empresa, calle, numeracion, renta_promedio, pct_aumento, cod_comuna, cod_region)
SELECT seq_compania.NEXTVAL, 'Empresa C', 'Av. Central', 789, 750000, 0.04, id_comuna, cod_region
FROM COMUNA
WHERE comuna_nombre = 'Concepción';

INSERT INTO COMPANIA (id_empresa, nombre_empresa, calle, numeracion, renta_promedio, pct_aumento, cod_comuna, cod_region)
SELECT seq_compania.NEXTVAL, 'Empresa D', 'Calle del Sol', 101, 820000, 0.05, id_comuna, cod_region
FROM COMUNA
WHERE comuna_nombre = 'La Serena';

INSERT INTO COMPANIA (id_empresa, nombre_empresa, calle, numeracion, renta_promedio, pct_aumento, cod_comuna, cod_region)
SELECT seq_compania.NEXTVAL, 'Empresa E', 'Av. Las Flores', 202, 870000, 0.06, id_comuna, cod_region
FROM COMUNA
WHERE comuna_nombre = 'Antofagasta';

INSERT INTO COMPANIA (id_empresa, nombre_empresa, calle, numeracion, renta_promedio, pct_aumento, cod_comuna, cod_region)
SELECT seq_compania.NEXTVAL, 'Empresa F', 'Calle Principal', 303, 780000, 0.04, id_comuna, cod_region
FROM COMUNA
WHERE comuna_nombre = 'Temuco';

INSERT INTO COMPANIA (id_empresa, nombre_empresa, calle, numeracion, renta_promedio, pct_aumento, cod_comuna, cod_region)
SELECT seq_compania.NEXTVAL, 'Empresa G', 'Av. Libertad', 404, 910000, 0.07, id_comuna, cod_region
FROM COMUNA
WHERE comuna_nombre = 'Puerto Montt';

SELECT 
    nombre_empresa AS "Nombre empresa",
    calle || ' ' || numeracion AS "Direccion",
    renta_promedio AS "Renta promedio",
    renta_promedio * (1+pct_aumento) AS "Simulacion de renta"
    FROM COMPANIA;
    

SELECT 
    id_empresa AS "ID Empresa",
    nombre_empresa AS "Nombre Empresa",
    renta_promedio AS "Renta Promedio Actual",
    pct_aumento * 1.15 AS "Pct aumentado en 15%",
    renta_promedio * (1 + pct_aumento * 1.15) AS "Renta Promedio Incrementada"
FROM COMPANIA
ORDER BY 
    renta_promedio ASC,
    nombre_empresa DESC;
    